import { Cliente } from "./types";

function haceDias(dias: number): string {
  const d = new Date();
  d.setDate(d.getDate() - dias);
  return d.toISOString().slice(0, 10);
}

function enDias(dias: number): string {
  const d = new Date();
  d.setDate(d.getDate() + dias);
  return d.toISOString().slice(0, 10);
}

export function crearClientesDeEjemplo(): Cliente[] {
  return [
    {
      id: "c1",
      nombre: "Laboratorios Andina",
      servicio: "Soluciones de inteligencia artificial",
      monto: 4500000,
      etiqueta: "Farmacéutica",
      responsable: "Andrea",
      etapa: "prospecto",
      fechaProximoContacto: enDias(3),
      fechaUltimoContacto: haceDias(2),
      progreso: 0,
      notas: [{ id: "n1", fecha: haceDias(2), texto: "Primer contacto, interesados en un modelo predictivo de demanda de stock." }],
    },
    {
      id: "c2",
      nombre: "Energía del Sur SA",
      servicio: "Dashboards e información en tiempo real",
      monto: 6200000,
      etiqueta: "Energía",
      responsable: "Matías",
      etapa: "prospecto",
      fechaProximoContacto: enDias(5),
      fechaUltimoContacto: haceDias(18),
      progreso: 0,
      notas: [],
    },
    {
      id: "c3",
      nombre: "TransLog Argentina",
      servicio: "Integración y automatización de datos",
      monto: 5000000,
      etiqueta: "Logística",
      responsable: "Martín",
      etapa: "propuesta",
      fechaProximoContacto: enDias(2),
      fechaUltimoContacto: haceDias(4),
      progreso: 0,
      notas: [{ id: "n2", fecha: haceDias(4), texto: "Se envió la propuesta de integración de datos de flota y depósitos." }],
    },
    {
      id: "c4",
      nombre: "Distribuidora Norte",
      servicio: "Calidad y seguridad de datos",
      monto: 3800000,
      etiqueta: "Distribución",
      responsable: "Andrea",
      etapa: "propuesta",
      fechaProximoContacto: enDias(1),
      fechaUltimoContacto: haceDias(20),
      progreso: 0,
      notas: [],
    },
    {
      id: "c5",
      nombre: "Droguería Litoral",
      servicio: "Dashboards e información en tiempo real",
      monto: 7500000,
      etiqueta: "Farmacéutica",
      responsable: "Matías",
      etapa: "activo",
      fechaProximoContacto: enDias(7),
      fechaUltimoContacto: haceDias(3),
      progreso: 65,
      notas: [
        { id: "n3", fecha: haceDias(20), texto: "Primer sprint: tablero ejecutivo con ventas y stock entregado." },
        { id: "n4", fecha: haceDias(3), texto: "Validando fuentes de datos del depósito central." },
      ],
    },
    {
      id: "c6",
      nombre: "PetroCuyo",
      servicio: "Integración y automatización de datos",
      monto: 12000000,
      etiqueta: "Energía",
      responsable: "Martín",
      etapa: "activo",
      fechaProximoContacto: enDias(4),
      fechaUltimoContacto: haceDias(6),
      progreso: 40,
      notas: [{ id: "n5", fecha: haceDias(6), texto: "Integrando datos de sensores de planta, en revisión con IT del cliente." }],
    },
    {
      id: "c7",
      nombre: "Comercial Rioplatense",
      servicio: "Desarrollo de productos digitales",
      monto: 5600000,
      etiqueta: "Distribución",
      responsable: "Andrea",
      etapa: "activo",
      fechaProximoContacto: enDias(10),
      fechaUltimoContacto: haceDias(16),
      progreso: 85,
      notas: [],
    },
    {
      id: "c8",
      nombre: "AgroInversiones SA",
      servicio: "Soluciones de inteligencia artificial",
      monto: 9000000,
      etiqueta: "Finanzas",
      responsable: "Matías",
      etapa: "cerrado",
      fechaProximoContacto: enDias(30),
      fechaUltimoContacto: haceDias(9),
      progreso: 100,
      notas: [{ id: "n6", fecha: haceDias(9), texto: "Modelo de scoring entregado, quedó soporte mensual." }],
      resultado: "ganado",
      notaCierre: "Modelo de scoring entregado y en producción; el cliente contrató soporte mensual.",
    },
    {
      id: "c9",
      nombre: "Rutas del Plata",
      servicio: "Calidad y seguridad de datos",
      monto: 4200000,
      etiqueta: "Logística",
      responsable: "Martín",
      etapa: "cerrado",
      fechaProximoContacto: enDias(60),
      fechaUltimoContacto: haceDias(12),
      progreso: 100,
      notas: [{ id: "n8", fecha: haceDias(12), texto: "El cliente avisó que frenan el proyecto por recorte de presupuesto." }],
      resultado: "perdido",
      notaCierre: "Se pausó por un recorte de presupuesto interno antes de firmar el contrato. No se llegó a trabajar juntos.",
    },
    {
      id: "c10",
      nombre: "Capital Andino",
      servicio: "Dashboards e información en tiempo real",
      monto: 6800000,
      etiqueta: "Finanzas",
      responsable: "Andrea",
      etapa: "cerrado",
      fechaProximoContacto: enDias(45),
      fechaUltimoContacto: haceDias(25),
      progreso: 100,
      notas: [{ id: "n7", fecha: haceDias(25), texto: "Buenos resultados con el tablero de riesgo, cliente conforme." }],
      resultado: "ganado",
      notaCierre: "Tablero de riesgo entregado a tiempo; el cliente renovó el contrato por un año más.",
    },
    {
      id: "c11",
      nombre: "Ferretera del Interior",
      servicio: "Integración y automatización de datos",
      monto: 3200000,
      etiqueta: "Distribución",
      responsable: "Matías",
      etapa: "cerrado",
      fechaProximoContacto: enDias(90),
      fechaUltimoContacto: haceDias(40),
      progreso: 100,
      notas: [{ id: "n9", fecha: haceDias(40), texto: "El cliente pidió posponer todo por una reestructuración interna." }],
      resultado: "perdido",
      notaCierre: "Después de la propuesta técnica, el cliente decidió posponer el proyecto por una reestructuración interna. No se firmó nada.",
    },
    {
      id: "c12",
      nombre: "Clínica San Rafael",
      servicio: "Dashboards e información en tiempo real",
      monto: 5100000,
      etiqueta: "Farmacéutica",
      responsable: "Martín",
      etapa: "cerrado",
      fechaProximoContacto: enDias(120),
      fechaUltimoContacto: haceDias(55),
      progreso: 100,
      notas: [{ id: "n10", fecha: haceDias(55), texto: "Entrega final del tablero de turnos y ocupación, arrancó soporte trimestral." }],
      resultado: "ganado",
      notaCierre: "Implementamos el tablero de turnos y ocupación; siguen siendo clientes con soporte trimestral.",
    },
  ];
}
